#!/bin/sh
# Pre-commit hook that compiles the main document and pushes to GDrive.
set -e

# Recompile main PDF.
main=`git config --local tex.main`
git checkout ${main}.pdf
make all && git add -f ${main}.pdf

# Upload main PDF to Google Drive.
reponame=`basename -s .git $(git config --get remote.origin.url)`
gdrivedir=`git config --local tex.gdrivedir`
cp ${main}.pdf $gdrivedir/
cd $gdrivedir
drive push -no-prompt ${main}.pdf
